### ISSUE TITLE
Batch watering

### ISSUE THREAD

**Issue by sentience** [sh00t2kill/linktap_local_http_component#17]
Although I agree that managing Linktap schedules via Home Assistant, I'd like to be able to start/stop batch watering programs that I've configured in the Linktap app from Home Assistant. Is that available via the API?

**Comment by sh00t2kill** [comment]
You can set and modify schedules, but it's clunky and doesn't sync with what's configured in the linktap app.

So I don't think that's possible, but I will double check the API documentation.

**Comment by sh00t2kill** [comment]
@sentience FWIW i added a node red flow to do "batch watering" -- happy to share this with you if  you use node red and would find it useful.

the flow creates a switch in HA, when the switch is triggered, it starts watering tap by tap until that tap finishes (so -- for the duration its configured for at the time of starting) and then turns the switch off at the end.

turning the switch off during the batch watering flow will also stop anything currently watering.

**Comment by sh00t2kill** [comment]
@sentience would there be value in a service that accepts a duration, and waters all taps 1 by 1 for that duration?

**Comment by bradkemper** [comment]
Could you just create automations that are triggered by times, with conditions that the be on certain days of the week? You could also add conditions regarding rain forecast, I think. 

The UI/UX and graphic design of the app is soooooo terrible that I generally try to avoid opening it, and would rather do everything from HA.

**Comment by bradkemper** [comment]
It looks like this should be able to integrate well with https://github.com/petergridge/Irrigation-V5, which has a custom card, and which in tern integrates with https://github.com/petergridge/openweathremaphistory so that you don't water when there has been, or will be, enough rain to do the job.

**Comment by sh00t2kill** [comment]
@bradkemper Yeah this is why i haven't implemented any sort of of scheduling within HA, because there are a myriad of other ways to do it.

I did start looking at a service which could do something similar to the batch watering, available in the Linktap app, but I just don't see a whole lot of value in it, and it does not persist past a HA restart.

**Comment by sh00t2kill** [comment]
Im going to close this because I dont think its something I will ever implement.
I dont like how HA deals with scheduled events -- its basically just an asyncio wait, so it doesnt  persist on a restart.
