### ISSUE TITLE
Add Controller Fails to Setup

### ISSUE THREAD

**Issue by y2kdread** [sh00t2kill/linktap_local_http_component#18]
Hi,

I setup integration in HACS and added the LinkTap gateway using a IP address that has a DHCP reservation on my router. When the integration tries to setup, it fails saying it cannot connect to device.

![Screenshot 2023-12-12 092745](https://github.com/sh00t2kill/linktap_local_http_component/assets/52291071/4a965f1c-6e63-4b0f-bb60-ea0ccd03adb6)

**Comment by sh00t2kill** [comment]
Can you please supply log information?

Have you enabled local http api on the gateway, and does your version match what's mentioned in the read me?

**Comment by y2kdread** [comment]
It did end up being that I hadn't enabled the API, I just did that and it worked perfectly. Thanks!
