### ISSUE TITLE
Removing old linktaps

### ISSUE THREAD

**Issue by gkyprios** [sh00t2kill/linktap_local_http_component#33]
Hey guys,

How do you remove an old Linktap from the integration? I removed one from the App that I wasnt using and put it into storage for now.

It wont delete if you use the three dots menu on the device:

![image](https://github.com/sh00t2kill/linktap_local_http_component/assets/81947775/57ffc65f-d28e-4ff7-a309-b8f95b6fef17)

It just stays visible if you try to delete it:

![image](https://github.com/sh00t2kill/linktap_local_http_component/assets/81947775/12fce0e2-003b-4c18-8e06-6658caffd19c)

I could delete all the entities but the device remains:

![image](https://github.com/sh00t2kill/linktap_local_http_component/assets/81947775/f0a40ccb-8bcd-4141-a02c-68c0d4f2b83c)

I've tried rebooting the Gateway device, restarting the HA Integration and restarting Home Assistant. But the old Linktap device remains visible despite all of this.

GK

**Comment by sh00t2kill** [comment]
If you delete the integration, restart HA, and then re-add the integration, does the device and related entities come back?

**Comment by gkyprios** [comment]
Yep, that did the trick. Thank you!
