### ISSUE TITLE
Switch and number entities not matching

### ISSUE THREAD

**Issue by coolhansen** [sh00t2kill/linktap_local_http_component#44]
I tried to change the standard duration for watering for different TapLinker. All the devices I changed to less than 15 min are working well, all the devices I changed to more than 15 min are stopping nethertheless  after 15 min.

**Comment by sh00t2kill** [comment]
Odd. I assume you mean by adjusting the number entities?

The ones that stop at 15, do they also work if you set them to less than 15?

Each switch entity has an attribute called Default Time. Is this set to true?

There is also a watering duration attribute. Does this match the value set in your number entity?
Does the duration entity attribute match the entity id of the created number?

It does some name matching to link the number with the switch, maybe that isn't working.

**Comment by coolhansen** [comment]
Yes, I mean the number entities.
No, the  ones that stop at 15, do not work if I set them to less than 15.
The attribute Default Time ist set on true for the not working and false fore the working. May I must change this? Where?

This works:
<img width="427" alt="Bildschirmfoto 2024-04-15 um 16 53 52" src="https://github.com/sh00t2kill/linktap_local_http_component/assets/77995245/75f4cc6a-7905-45e7-b5e7-4969a7c32d12">

This works not:
<img width="427" alt="Bildschirmfoto 2024-04-15 um 16 54 58" src="https://github.com/sh00t2kill/linktap_local_http_component/assets/77995245/fd63706f-f30e-40da-baa8-003f93037198">

**Comment by sh00t2kill** [comment]
What's the entity_id of the number entity?

**Comment by coolhansen** [comment]
number.linktap_08_paul_str_hint_perl_watering_duration Is the id

**Comment by sh00t2kill** [comment]
Thanks!
The issue was as i expected. It should be fixed in v0.5.4
