### ISSUE TITLE
No speed or volume 

### ISSUE THREAD

**Issue by bradkemper** [sh00t2kill/linktap_local_http_component#46]
The sensors for speed and volume for my LinkTap always seem to be zero. I usually use the “Irrigation Controller” integration to turn it on and off, and that part functions. But I think that maybe because it can’t measure the flow via speed and volume sensors, it never knows when to turn off. That’s a theory anyway. The “Is Watering” sensor seems to work fine, but Irrigation Controller seems to not look at binary sensors for that info, I guess. Either way, when the tap in on, the Local LinkTap speed and volume entities still reports zero. 

I used the “visit” link in your integration to Enable local HTTP API, and rebooted (I missed that step initially), but this didn’t seem to make a difference.

**Comment by sh00t2kill** [comment]
What sort of linktap devices do you have ?
Not all of them have the measurement sensors in them.

For example; I have
1x G1 - No volume or speed. This is the old original device they released, it doesnt have a water flow meter.
1x D1 - This has an inbuilt water flow meter and does report speed and volume
1x 4 zone valve linker - This did not have speed and volume until i added the additional flow meters.


Are you getting flow rates etc in the link tap app ?

**Comment by bradkemper** [comment]
Ah, that makes sense then. I have two G1S’s.

**Comment by sh00t2kill** [comment]
Yeah.
The FAW states that the G2S is basically a G1S with a flow meter.
https://www.link-tap.com/#!/faq/en/What-is-the-difference-between-the-G1S-and-G2S-water-timers
