### ISSUE TITLE
HA - Failed to Setup

### ISSUE THREAD

**Issue by danbayliss** [sh00t2kill/linktap_local_http_component#5]
I've just received my D1 and I'm trying to get this working but it doesn't seem to want to connect. I've tried entering http://192.168.0.71 and just 192.168.0.71 but it's still the same. Attached are some screenshots and logs, can you help?

**Gateway** Is the Server URL meant to be the URL of my gateway or HA? At the moment it's my gateway
![h1TMpAR](https://github.com/sh00t2kill/linktap_local_http_component/assets/54558493/d824d16e-18a9-4325-9d16-767081dbb4b1)

**HA Error**
![V9FpV3j](https://github.com/sh00t2kill/linktap_local_http_component/assets/54558493/d8712a9a-71a0-4f4f-8c8b-b08e07c47b9c)

**Log**
```2023-09-09 17:55:48.168 DEBUG (MainThread) [custom_components.linktap.config_flow] Starting async_step_user of Linktap Local Integration
2023-09-09 17:56:09.262 DEBUG (MainThread) [custom_components.linktap.config_flow] Starting async_step_user of Linktap Local Integration
2023-09-09 17:56:09.283 DEBUG (MainThread) [custom_components.linktap] Found GW_ID: E597DB1D004B1200
2023-09-09 17:56:09.303 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Linktap Local Integration for linktap
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/linktap/__init__.py", line 50, in async_setup_entry
    "devs": gateway_config["end_dev"],
            ~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'end_dev'```

**Comment by sh00t2kill** [comment]
You enter just the IP, not http:// etc.

It looks like your gateway is out of date. Contact support and ask them to update it.

Note that the required version is in the readme

**Comment by danbayliss** [comment]
Thanks. I have emailed support. I don't see the required version in the readme?

**Comment by sh00t2kill** [comment]
@danbayliss apologies I got confused between the repo and the forum thread.

If you have a version of x060820” (x is S or G, indicating that the firmware belongs to GW-01 or GW-02, respectively) or higher, it should work.

**Comment by danbayliss** [comment]
My gateway has been updated to G060835 and the integration is now working, thanks!

**Comment by sh00t2kill** [comment]
Awesome.
I'll add some error handling with a specific error to catch that.
