### ISSUE TITLE
Default Time and Manual watering

### ISSUE THREAD

**Issue by derhally** [sh00t2kill/linktap_local_http_component#50]
I just configured the LinkTap integration and everything is working except I can't seem to figure out how to switch the "Default Time" to false and have it honor my water duration setting.

![image](https://github.com/sh00t2kill/linktap_local_http_component/assets/13053772/e0136e15-4d3c-4b7c-8342-94438578f165)

I thought it was false before, but when I reloaded the integration it was back to true.

**Comment by sh00t2kill** [comment]
Does the duration entity listed as an attribute match the entity created by the integration?

I've only seen this happen when there's an issue with the name matching

**Comment by derhally** [comment]
I don't know what caused it, but the names were not matching.   Not sure if the issue was that I imported the linktapper then renamed it in home assistant and then I went back to the LinkTap app and renamed it there to match the name in Home Assistant and there was some delay in everything being in sync.

I saw these in the debug logs

```
2024-07-05 22:02:15.503 DEBUG (MainThread) [custom_components.linktap.switch] Entity number.linktap_taplinker_watering_duration not found -- setting default
2024-07-05 22:02:15.503 DEBUG (MainThread) [custom_components.linktap.switch] Set duration:15
```

I unloaded the integration got everything named on the TapLink side, then added the integration back and everything seems to be working as expected.

**Comment by sh00t2kill** [comment]
That's a good point; renaming the entity_id for the number will break the integration. 

I'll look at improving how that works in the future.

**Comment by argoon38** [comment]
Hi,
I've got the same issue. Actually, I've got 3 Lintap and all have the same attribute 
`duration_entity: number.linktap_taplinker_watering_duration`

@derhally, what do you mean by 'I unloaded the integration'? Do you mean Reload action?

**Comment by sh00t2kill** [comment]
> Hi, I've got the same issue. Actually, I've got 3 Lintap and all have the same attribute `duration_entity: number.linktap_taplinker_watering_duration`
> 
> @derhally, what do you mean by 'I unloaded the integration'? Do you mean Reload action?

In a nutshell, renaming things breaks the integration horribly. Don't do it.

Make sure your taps are named in linktap as you want them. Delete the integration and re-add it.

**Comment by sh00t2kill** [comment]
I added this to the FAQ's.

I have a feeling that fixing it properly may cause entities to get re-created, but I will look at it when i get some time.
